name: Auto-assign PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign:
    permissions:
      pull-requests: write
    uses: tha-guy-nate/tha-github-workflows/.github/workflows/auto-assign-pr.yml@main
