name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  pre-commit:
    uses: tha-guy-nate/tha-github-workflows/.github/workflows/pre-commit.yml@main

  ci:
    uses: tha-guy-nate/tha-github-workflows/.github/workflows/python-ci.yml@main
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13"]'
